#!/usr/bin/env python
# (c) Copyright 2023 Premier Heart, LLC

import json
import requests
import os
import random
import sys
from datetime import datetime

TOKEN_PATH_KEY = 'MCG_API_TOKEN_FILE'
TOKEN_KEY = 'MCG_API_TOKEN'

def get_api_token():
    if TOKEN_KEY in os.environ:
        return os.environ[TOKEN_KEY]
    elif TOKEN_PATH_KEY in os.environ:
        with open(os.environ[TOKEN_PATH_KEY], 'r') as f:
            return f.read().strip()
    else:
        raise "Missing token! Set either MCG_API_TOKEN or MCG_API_TOKEN_FILE in environment."

def send_api_request(server_url, token, data):
    header = { 'Authorization': token,
               'Content-Type': 'application/json' }
    response = requests.post(url=server_url, headers=header, json=data)
    return response

def build_request(inputs):
    return {
      "object-type": "analysis-request",
      "analysis": {
        "type": "ecg-tracing-quality",
        "options": { }
      },
      "output": {
      },
      "input": inputs,
      "comment": "(FAKE DATA) Generated by " + os.path.basename(__file__)
    }

def input_for_ecg_json(json_str, age=40, gender='M'):
    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    return {
      "type": "ecg",
      "format": "json",
      "timestamp": ts,
      "age": age,
      "gender": gender,
      "data": json.loads(json_str)
    }

def decode_response(resp):
    if resp.status_code != 200:
        return {
                "object-type": "http-error",
                "timestamp": str(datetime.now),
                "message": "Unknown error: HTTP %d" % resp.status_code
        }
    return json.loads(resp.text)

def print_results_summary(res, indent="\t"):
    tq_h = res['tracing-quality']
    stats_h = res['ecg-stats']
    leads = list(stats_h.keys())
    h = tq_h['all']

    print(indent + "Tracing Quality: %d" % (h['tracing quality']))
    print(indent + indent + "**  Baseline: %d Noise: %d Range: %d" % (h['TQ baseline'], h['TQ noise'],  h['TQ range']))
    for lead in leads:
        h = tq_h[lead]
        print(indent + indent + "%s  Baseline: %d Noise: %d Range: %d" % (lead, h['TQ baseline'], h['TQ noise'],  h['TQ range']))

    print(indent + "ECG Details:")
    for lead in leads:
        h = stats_h[lead]
        print(indent + indent + "%s  Count: %d  High: %d  Low: %d  Baseline: %d  Total: %d  Peak Count: %d  Voltage: %0.2f  PPV: %d" % (lead, h['count'], h['high'], h['low'], h['baseline'], h['total'], h['peak_count'], h['voltage'], h['ppv']))


if __name__ == '__main__':
    url = "https://api.premierheart.com/api/v1/analyze"
    if len(sys.argv) > 1:
        url = sys.argv[1]

    inputs = [ ]
    for x in range(3):
        fname = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data', ("ecg_%d.json" % (x+1)))
        with open(fname, 'r') as f:
            inputs.append(input_for_ecg_json(f.read()))
        print("Read input: %s" % (fname))

    data = build_request( inputs )
    with open("data/analysis-request.ecg-files.tracing-quality.json", 'w') as f:
        f.write(json.dumps(data))

    token = get_api_token()
    resp = send_api_request(url, token, data)
    results = decode_response(resp)

    if results['object-type'] != 'analysis-result':
        print("Unexpected return value from API server:")
        for k,v in results.items():
            print("\t%s: %s" % (k, v))
        sys.exit()

    # save to disk:
    with open("data/analysis-results.ecg-files.tracing-quality.json", 'w') as f:
        f.write(json.dumps(results))

    if 'comment' in results:
        print("Comment: " % results['comment'])
    print("Results Summary:")
    for k,v in results.items():
        if k == 'results':
            print_results_summary(v, "\t")
        elif k != 'attachments':
            print("\t%s: %s" % (k, str(v)))
